### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jayaramki**
added code usage of data-showlinenumber and data-showfooter attributes

### CODE REVIEW

**Comment by kashif-umair** [comment]
Hi @Jayaramki,

Thanks for the contribution, but can you please make the following changes in your PR?

Replace `data-showlinenumbers` with `data-showLineNumbers` in README.md. Notice the Camel Case letters.

Similiarly replace `data-showfooter` with `data-showFooter`.

Thanks,

**Comment by Jayaramki** [comment]
yeah... I changed that. Check it now.

**Comment by kashif-umair** [comment]
Thanks for the contribution. Merging it now :)

**Comment by Jayaramki** [comment]
Thanks...
This is my first contribution to open source project. I'm feeling happy... This is encouraging me to contribute more to open source...
Once again Thanks @kashif-umair

**Comment by kashif-umair** [comment]
Please suggest if you have any ideas to make this plugin better. I'll be happy to help you with that idea and I'll be glad to see your further contribution to this project. Thanks.

**Comment by Jayaramki** [comment]
yeah sure @kashif-umair ... If you have free time visit my first repository too. This is about showing rss feed of given url like blogger rss feed widget. But, I gave two additional option to control over feed item count and showing content snippet. https://github.com/Jayaramki/display-feed-js

**Pull request merged**
